### ISSUE TITLE
Improve lint and formatting for code and commits

### ISSUE THREAD

**Issue by hansfpc** [hansfpc/whoami#1]
## todo

- [ ] add enough EsLint rules
- [ ] add Prettier formatting or something else
- [ ] add Husky and lint-staged
- [ ] add Code Rules github action
