### ISSUE TITLE
Enhance repository security

### ISSUE THREAD

**Issue by hansfpc** [hansfpc/whoami#2]
## todo

- [ ] Protect `main` branch
- [ ] Add `Code Rules` github action
- [ ] Add `Semantic Pull Request` Github Bot
